### ISSUE TITLE
Thanks for the swallow script

### ISSUE THREAD

**Issue by ghost** [yousufinternet/config-files#1]
Do you also have the issue where you can only create windows around the parent of the swallowed node ?

**Comment by yousufinternet** [comment]
Wow.. My first issue on github, please give me some time to cherish this moment :P 
I am not sure I get your question though, can you clarify it a little bit?

**Comment by ghost** [comment]
I'll try my best.
Take for example this screenshot.
https://files.catbox.moe/5yyo5q.png
Currently if open a new term using the bspwm specific keys it will split like this.
https://files.catbox.moe/zbz8mv.png

The opposite would happen if the terminal on the right would have been an application that swallowed a terminal. The new terminal window would have opened to the left.

**Comment by ghost** [comment]
I eventually switched to https://github.com/JopStro/bspswallow, sorry I couldn't better pinpoint my issue.

**Comment by yousufinternet** [comment]
Sorry I was unable to help, I wrote the script for personal use any way, and shared it on reddit for inspiration only. 
Thanks for opening the issue
